
FISH_TANK_IP = "10.42.0.1"
FISH_TANK_PORT = 5000

FISH_SPEED_DEFAULT = 5
OVERRIDE_SPEED_DEFAULT = 5

LED_R_DEFAULT = 255
LED_G_DEFAULT = 255
LED_B_DEFAULT = 255

# TCP command
TCP_DELIMITER = ";"

TCP_FORWARD = "FWD"
TCP_BACKWARD = "BACK"
TCP_LEFT = "LEFT"
TCP_RIGHT = "RIGHT"
TCP_ROTATE_CW = "RCW"
TCP_ROTATE_CCW = "RCC"

TCP_DISABLE = "DISABLE"
TCP_ENABLE = "ENABLE"

TCP_SET_FISH_SPEED_HEADER = "FISH" # followed by a number
TCP_SET_OVERRIDE_SPEED_HEADER = "OVERRIDE" # followed by a number

TCP_LED_RGB = "RGB" # followed by 3 numbers [0, 255] delimited by 2 commas
TCP_LED_PARTY = "PARTY"
